require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClimbsController do

  # This should return the minimal set of attributes required to create a valid
  # Climb. As you add validations to Climb, be sure to
  # update the return value of this method accordingly.
  let(:valid_attributes) {     
    style = create(:style)
    area = create(:area)
    attributes_for(:climb, style_id: style.id, area_id: area.id, name: "MyString") 
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClimbsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all climbs as @climbs" do
      climb = Climb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:climbs).should eq([climb])
    end
  end

  describe "GET show" do
    it "assigns the requested climb as @climb" do
      climb = Climb.create! valid_attributes
      get :show, {:id => climb.to_param}, valid_session
      assigns(:climb).should eq(climb)
    end
  end

  describe "GET new" do
    it "assigns a new climb as @climb" do
      get :new, {}, valid_session
      assigns(:climb).should be_a_new(Climb)
    end
  end

  describe "GET edit" do
    it "assigns the requested climb as @climb" do
      climb = Climb.create! valid_attributes
      get :edit, {:id => climb.to_param}, valid_session
      assigns(:climb).should eq(climb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Climb" do
        expect {
          post :create, {:climb => valid_attributes}, valid_session
        }.to change(Climb, :count).by(1)
      end

      it "assigns a newly created climb as @climb" do
        post :create, {:climb => valid_attributes}, valid_session
        assigns(:climb).should be_a(Climb)
        assigns(:climb).should be_persisted
      end

      it "redirects to the created climb" do
        post :create, {:climb => valid_attributes}, valid_session
        response.should redirect_to(Climb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved climb as @climb" do
        # Trigger the behavior that occurs when invalid params are submitted
        Climb.any_instance.stub(:save).and_return(false)
        post :create, {:climb => { "name" => "invalid value" }}, valid_session
        assigns(:climb).should be_a_new(Climb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Climb.any_instance.stub(:save).and_return(false)
        post :create, {:climb => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested climb" do
        climb = Climb.create! valid_attributes
        # Assuming there are no other climbs in the database, this
        # specifies that the Climb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Climb.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => climb.to_param, :climb => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested climb as @climb" do
        climb = Climb.create! valid_attributes
        put :update, {:id => climb.to_param, :climb => valid_attributes}, valid_session
        assigns(:climb).should eq(climb)
      end

      it "redirects to the climb" do
        climb = Climb.create! valid_attributes
        put :update, {:id => climb.to_param, :climb => valid_attributes}, valid_session
        response.should redirect_to(climb)
      end
    end

    describe "with invalid params" do
      it "assigns the climb as @climb" do
        climb = Climb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Climb.any_instance.stub(:save).and_return(false)
        put :update, {:id => climb.to_param, :climb => { "name" => "invalid value" }}, valid_session
        assigns(:climb).should eq(climb)
      end

      it "re-renders the 'edit' template" do
        climb = Climb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Climb.any_instance.stub(:save).and_return(false)
        put :update, {:id => climb.to_param, :climb => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested climb" do
      climb = Climb.create! valid_attributes
      expect {
        delete :destroy, {:id => climb.to_param}, valid_session
      }.to change(Climb, :count).by(-1)
    end

    it "redirects to the climbs list" do
      climb = Climb.create! valid_attributes
      delete :destroy, {:id => climb.to_param}, valid_session
      response.should redirect_to(climbs_url)
    end
  end

end
