source 'https://rubygems.org'
ruby "2.0.0"
gem 'rails', '4.0.2'

gem 'uglifier', '>= 1.0.3'
gem "compass-rails", "~> 1.1.2"

gem "thin", ">= 1.5.0", :group => :production
gem "rspec-rails", ">= 2.11.4", :group => [:development, :test]
gem "email_spec", ">= 1.4.0", :group => :test
gem "launchy", ">= 2.1.2", :group => :test
gem "capybara", ">= 2.0.1", :group => :test
gem "factory_girl_rails", ">= 4.1.0", :group => [:development, :test]
gem "devise", :git => "git://github.com/plataformatec/devise.git"
gem "cancan", :git => 'git://github.com/ryanb/cancan'
gem "rolify", :git => 'git://github.com/EppO/rolify'
gem "figaro", ">= 0.5.0"
gem "binding_of_caller", ">= 0.6.8", :group => :development
gem "hub", ">= 1.10.2", :require => nil, :group => [:development]
gem 'annotate', ">=2.5.0"
gem "therubyracer"
gem 'debugger', :group => [:development]
gem "faker", "~> 1.1.2", :group => [:development, :test]
gem 'pg'
gem 'friendly_id', '~> 5.0.0'
gem 'country_select', :git => 'git://github.com/stefanpenner/country_select'
gem 'newrelic_rpm', :group => [:production]
gem 'auto_html', :git => 'git://github.com/Dhaulagiri/auto_html.git'
gem 'counter_culture', '~> 0.1.7'
gem 'meta-tags', :require => 'meta_tags'
gem 'gon'
gem 'pg_search'
gem 'carmen'
gem 'rails_12factor', group: :production
gem 'active_model_serializers'

group :test do
  gem "guard-rspec"
  gem "database_cleaner"
end
